### ISSUE TITLE
Uninformative error in automateDataPreparation

### ISSUE THREAD

**Issue by beckerbenj** [sachseka/eatPrep#15]
When `automateDataPreparation()` is called with `NAs` in `case-id`, the resulting error message is rather uninformative:

`ID variable NAnot found in dataset.`

The function seems to internally assume that an empty excel column should result in `oldIDs` being `NULL`, which is not the case (see `if(is.null(oldIDs))` check).

**Comment by beckerbenj** [comment]
to do: update snapshots locally; this should fix fails in Github Action

**Comment by sachseka** [comment]
fixed
