### ISSUE TITLE
Breaking change in cli

### ISSUE THREAD

**Issue by beckerbenj** [sachseka/eatPrep#18]
Somewhere in between `cli` `3.4.0` and `3.6.1` breaking changes were introdued. More specifically, the snapshots apparently were all starting with `message <cliMessage>`, for example

```
Code
  scoreDataTest(testScore)
Message <cliMessage>
```

but should now be simply `Message`. This triggers the >200 errors in the Github action workflows in the current development branch. My experience with `testthat` snapshots is limited, but I suppose one would have to simply update the snapshots locally with a newish installation of `cli` (note that updating `cli` via RStudio can be tricky).

This is a bit unfortunate, as `eatPrep` does not really depend on `cli >3.6.1` (or whatever version it is); but running `eatPrep` tests/R CMD *does* depend on `cli >3.6.1`.

**Comment by sachseka** [comment]
fixed with last update
