### ISSUE TITLE
Implementation of checkmate checks

### ISSUE THREAD

**Issue by sachseka** [sachseka/eatPrep#24]

**Comment by grewered** [comment]
is there an overview/handbook for how the functions work or what kind of arguments they use, like for eatTools @sachseka ?
Because that helped a lot. If not I'll probably just going to have more questions.

**Comment by sachseka** [comment]
Please have a look at: i:\Methoden\02_IQB-interne_eat_Workshops\eatPrep_2021\eatPrep_2021-06-18.pdf + main description ("Aufbereitung von Datensätzen (Einlesen, Plausibilitätsprüfungen, Zusammenführen von Datensätzen, Missingbehandlung, Rekodieren, Aggregieren, Scoren und Schreiben von gelabelten SPSS-Datensätzen) unter Verwendung von in der IQB-Datenbank hinterlegten Informationen zu den Items und zum Testdesign. Diese werden mithilfe des ZKDaemon (siehe unten) aus der Datenbank extrahiert und in ein standardisiertes xlsx-Format geschrieben. Dieses xlsx-Format nutzt "eatPrep", um die Informationen aus der Datenbank nach R zu übertragen.")
Sorry, the vignette was never finished.

**Comment by grewered** [comment]
shall I just add checks in functions where they are no checks (like in eatTools)? or also rewrite them in functions, when rewriting them makes the code easier/more consistent?

**Comment by grewered** [comment]
shall I just add checks in functions where they are no checks (like in eatTools)? or also rewrite them in functions, when rewriting them makes the code easier/more consistent? @sachseka

**Comment by sachseka** [comment]
Überarbeitungen im Gange, @grewered und @sachseka sind dran

**Comment by sachseka** [comment]
@grewered Okay, finally, I think, checkmate implementation is completely completed -- would you mind to do the last merges? Thx
